// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0emO4vmguWS5jQi9sRIGNI45PRpFkOVo',
    appId: '1:459876301711:web:fb0c214928ca8d57bfa9fa',
    messagingSenderId: '459876301711',
    projectId: 'signin-a08e4',
    authDomain: 'signin-a08e4.firebaseapp.com',
    storageBucket: 'signin-a08e4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoafGRUVLqJlIJu7peoaLSy8_2Z5Cgs70',
    appId: '1:459876301711:android:14cc342efb9458a0bfa9fa',
    messagingSenderId: '459876301711',
    projectId: 'signin-a08e4',
    storageBucket: 'signin-a08e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfhkagjnA9vU8ITOQ-ywCwaAaoVbE7yZg',
    appId: '1:459876301711:ios:64ae1090b337b052bfa9fa',
    messagingSenderId: '459876301711',
    projectId: 'signin-a08e4',
    storageBucket: 'signin-a08e4.appspot.com',
    iosBundleId: 'com.example.signinPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfhkagjnA9vU8ITOQ-ywCwaAaoVbE7yZg',
    appId: '1:459876301711:ios:33f92fb91051f5afbfa9fa',
    messagingSenderId: '459876301711',
    projectId: 'signin-a08e4',
    storageBucket: 'signin-a08e4.appspot.com',
    iosBundleId: 'com.example.signinPage.RunnerTests',
  );
}
